### ISSUE TITLE
Better doc ?

### ISSUE THREAD

**Issue by Oli8** [ballantyno/CreateJSTextInput#1]
Hi,

good stuff bro, I needed that for a project but it would be a nice if you'd have a more detailed documentation and/or a better way to do stuff like how to retrieve the value of the input or to autofocus it.
I had to to look up the code and do some sketchy things to make it work.

Regards

**Comment by ballantyno** [comment]
The project was pretty much abandoned 9-10 months ago. 

It turns out you can achieve a lot of what I wanted with CSS and just overlaying on the canvas. 

I'll look to delete the project soon; as it's getting attention when it was never intended to do so.
