### ISSUE TITLE
some added features such as update properties

### ISSUE THREAD

**Issue by simongcc** [ballantyno/CreateJSTextInput#2]
Happy new year.

I have just downloaded, added some new features and finished the unfinished features in this addon.
Do you prefer I fork it or I make a merge request?
I really thanks for providing this blue print for solving the problem.

Features such as:

- support canvas with non original width such as "width:100%" by adding scale calculation
- changed the window.addEventListener to object.addEventListener instead and get e.nativeEvent for better control and avoid whole screen being effectively responding the event listener.
- finished the support to change the properties such as changing the textcolor etc
- added also some additional properties
- changed the algorithm for the padding

Thanks again for providing this.

**Comment by ballantyno** [comment]
Hi there,

Sorry for the long wait in a reply. I've not looked into this project for sometime. I don't really have any path forward. 

You're welcome to fork and continue the work. But as it stands I'm not looking to maintain or continue the work as I have other projects on the go and this one isn't of high priority for me. 

Best of luck.
